/* eslint-disable */
/* auto-generated by scripts/generate-modules.ts — do not edit manually */

export type ResourceAction = "add" | "del" | "delete" | "download" | "edit" | "find" | "findmain" | "fiscalize" | "get" | "notes" | "send" | "trigger" | "unfiscalize";

export type ResourceName = "companies" | "company_accounts" | "company_addresses" | "company_packs" | "contractors" | "declaration_body_jpkvat" | "declaration_body_pit" | "declaration_countries" | "documents" | "expenses" | "goods" | "interests" | "invoice_deliveries" | "invoice_descriptions" | "invoices" | "ledger_accountant_years" | "ledger_operation_schemas" | "notes" | "payment_cashboxes" | "payments" | "series" | "tags" | "taxregisters" | "term_groups" | "terms" | "translation_languages" | "user_companies" | "users" | "vat_codes" | "vehicle_run_rates" | "vehicles" | "warehouse_document_p_w" | "warehouse_document_p_z" | "warehouse_document_r" | "warehouse_document_r_w" | "warehouse_document_w_z" | "warehouse_document_z_d" | "warehouse_document_z_p_d" | "warehouse_document_z_p_m" | "warehouses" | "webhooks";

export type ActionDef = {
  method: string;
  wrapPayload?: boolean;
};

export type ResourceDefinition = {
  name: ResourceName;
  singularName: string;
  pluralName: string;
  actions: Record<string, ActionDef>;
};

export const RESOURCE_DEFINITIONS: Record<ResourceName, ResourceDefinition> = {
  "companies": {
    "name": "companies",
    "singularName": "company",
    "pluralName": "companies",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "company_accounts": {
    "name": "company_accounts",
    "singularName": "company_account",
    "pluralName": "company_accounts",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "company_addresses": {
    "name": "company_addresses",
    "singularName": "company_addresse",
    "pluralName": "company_addresses",
    "actions": {
      "findmain": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "company_packs": {
    "name": "company_packs",
    "singularName": "company_pack",
    "pluralName": "company_packs",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "contractors": {
    "name": "contractors",
    "singularName": "contractor",
    "pluralName": "contractors",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "declaration_body_jpkvat": {
    "name": "declaration_body_jpkvat",
    "singularName": "declaration_body_jpkvat",
    "pluralName": "declaration_body_jpkvat",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "declaration_body_pit": {
    "name": "declaration_body_pit",
    "singularName": "declaration_body_pit",
    "pluralName": "declaration_body_pit",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "declaration_countries": {
    "name": "declaration_countries",
    "singularName": "declaration_country",
    "pluralName": "declaration_countries",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "documents": {
    "name": "documents",
    "singularName": "document",
    "pluralName": "documents",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "download": {
        "method": "GET",
        "wrapPayload": false
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "expenses": {
    "name": "expenses",
    "singularName": "expense",
    "pluralName": "expenses",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "goods": {
    "name": "goods",
    "singularName": "good",
    "pluralName": "goods",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "interests": {
    "name": "interests",
    "singularName": "interest",
    "pluralName": "interests",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "invoice_deliveries": {
    "name": "invoice_deliveries",
    "singularName": "invoice_delivery",
    "pluralName": "invoice_deliveries",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "invoice_descriptions": {
    "name": "invoice_descriptions",
    "singularName": "invoice_description",
    "pluralName": "invoice_descriptions",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "invoices": {
    "name": "invoices",
    "singularName": "invoice",
    "pluralName": "invoices",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "download": {
        "method": "POST",
        "wrapPayload": false
      },
      "fiscalize": {
        "method": "GET",
        "wrapPayload": false
      },
      "unfiscalize": {
        "method": "GET",
        "wrapPayload": false
      },
      "send": {
        "method": "POST",
        "wrapPayload": true
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "ledger_accountant_years": {
    "name": "ledger_accountant_years",
    "singularName": "ledger_accountant_year",
    "pluralName": "ledger_accountant_years",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "ledger_operation_schemas": {
    "name": "ledger_operation_schemas",
    "singularName": "ledger_operation_schema",
    "pluralName": "ledger_operation_schemas",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "notes": {
    "name": "notes",
    "singularName": "note",
    "pluralName": "notes",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "payment_cashboxes": {
    "name": "payment_cashboxes",
    "singularName": "payment_cashboxe",
    "pluralName": "payment_cashboxes",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "payments": {
    "name": "payments",
    "singularName": "payment",
    "pluralName": "payments",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "series": {
    "name": "series",
    "singularName": "sery",
    "pluralName": "series",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "notes": {
        "method": "POST",
        "wrapPayload": true
      },
      "del": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "tags": {
    "name": "tags",
    "singularName": "tag",
    "pluralName": "tags",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "notes": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "taxregisters": {
    "name": "taxregisters",
    "singularName": "taxregister",
    "pluralName": "taxregisters",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "term_groups": {
    "name": "term_groups",
    "singularName": "term_group",
    "pluralName": "term_groups",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "notes": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "terms": {
    "name": "terms",
    "singularName": "term",
    "pluralName": "terms",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "notes": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "translation_languages": {
    "name": "translation_languages",
    "singularName": "translation_language",
    "pluralName": "translation_languages",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "user_companies": {
    "name": "user_companies",
    "singularName": "user_company",
    "pluralName": "user_companies",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "users": {
    "name": "users",
    "singularName": "user",
    "pluralName": "users",
    "actions": {
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "vat_codes": {
    "name": "vat_codes",
    "singularName": "vat_code",
    "pluralName": "vat_codes",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "vehicle_run_rates": {
    "name": "vehicle_run_rates",
    "singularName": "vehicle_run_rate",
    "pluralName": "vehicle_run_rates",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "vehicles": {
    "name": "vehicles",
    "singularName": "vehicle",
    "pluralName": "vehicles",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_p_w": {
    "name": "warehouse_document_p_w",
    "singularName": "warehouse_document_p_w",
    "pluralName": "warehouse_document_p_w",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_p_z": {
    "name": "warehouse_document_p_z",
    "singularName": "warehouse_document_p_z",
    "pluralName": "warehouse_document_p_z",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_r": {
    "name": "warehouse_document_r",
    "singularName": "warehouse_document_r",
    "pluralName": "warehouse_document_r",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_r_w": {
    "name": "warehouse_document_r_w",
    "singularName": "warehouse_document_r_w",
    "pluralName": "warehouse_document_r_w",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_w_z": {
    "name": "warehouse_document_w_z",
    "singularName": "warehouse_document_w_z",
    "pluralName": "warehouse_document_w_z",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_z_d": {
    "name": "warehouse_document_z_d",
    "singularName": "warehouse_document_z_d",
    "pluralName": "warehouse_document_z_d",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_z_p_d": {
    "name": "warehouse_document_z_p_d",
    "singularName": "warehouse_document_z_p_d",
    "pluralName": "warehouse_document_z_p_d",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouse_document_z_p_m": {
    "name": "warehouse_document_z_p_m",
    "singularName": "warehouse_document_z_p_m",
    "pluralName": "warehouse_document_z_p_m",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "POST",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  },
  "warehouses": {
    "name": "warehouses",
    "singularName": "warehouse",
    "pluralName": "warehouses",
    "actions": {
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      }
    }
  },
  "webhooks": {
    "name": "webhooks",
    "singularName": "webhook",
    "pluralName": "webhooks",
    "actions": {
      "add": {
        "method": "POST",
        "wrapPayload": true
      },
      "find": {
        "method": "GET",
        "wrapPayload": false
      },
      "get": {
        "method": "GET",
        "wrapPayload": false
      },
      "trigger": {
        "method": "GET",
        "wrapPayload": false
      },
      "edit": {
        "method": "PATCH",
        "wrapPayload": true
      },
      "delete": {
        "method": "DELETE",
        "wrapPayload": false
      }
    }
  }
} as Record<ResourceName, ResourceDefinition>;
