import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type PostmanItem = {
  name?: string;
  request?: {
    method?: string;
    url?: string | { raw?: string };
  };
  item?: PostmanItem[];
};

type ActionDef = {
  method: string;
  wrapPayload?: boolean;
};

type ResourceDefinition = {
  name: string;
  singularName: string;
  pluralName: string;
  actions: Record<string, ActionDef>;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const collectionPath = join(__dirname, "../postman/collection.json");
const outputPath = join(__dirname, "../src/modules/resources.generated.ts");

const NO_WRAP_ACTIONS = new Set([
  "find",
  "get",
  "delete",
  "findmain",
  "download",
  "fiscalize",
  "unfiscalize",
  "trigger",
  "del",
]);

const toSingular = (resource: string): string => {
  if (resource.endsWith("ies")) {
    return `${resource.slice(0, -3)}y`;
  }
  if (resource.endsWith("s")) {
    return resource.slice(0, -1);
  }
  return resource;
};

const parseResources = (items: PostmanItem[]): Map<string, ResourceDefinition> => {
  const resources = new Map<string, ResourceDefinition>();

  const walk = (nodes: PostmanItem[]) => {
    for (const node of nodes) {
      if (node.request) {
        const rawUrl =
          typeof node.request.url === "string"
            ? node.request.url
            : node.request.url?.raw;

        const path = rawUrl
          ?.replace(/\{\{host\}\}\/?/g, "")
          .replace("https://api2.wfirma.pl/", "")
          .split("?")[0];

        const match = path?.match(/^([^/]+)\/([^/]+)/);
        if (!match || !node.request.method) {
          continue;
        }

        const [, resource, action] = match;
        const method = node.request.method.toUpperCase();

        if (!resources.has(resource)) {
          const singularName = toSingular(resource);
          resources.set(resource, {
            name: resource,
            singularName,
            pluralName: resource,
            actions: {},
          });
        }

        const entry = resources.get(resource)!;
        entry.actions[action] = {
          method,
          wrapPayload: !NO_WRAP_ACTIONS.has(action),
        };
      }

      if (node.item?.length) {
        walk(node.item);
      }
    }
  };

  walk(items);
  return resources;
};

const collection = JSON.parse(readFileSync(collectionPath, "utf8")) as {
  item: PostmanItem[];
};

const resources = [...parseResources(collection.item).values()].sort((a, b) =>
  a.name.localeCompare(b.name),
);

const resourceNames = resources.map((r) => r.name);

const file = `/* eslint-disable */
/* auto-generated by scripts/generate-modules.ts — do not edit manually */

export type ResourceAction = ${resourceNames
  .flatMap((name) =>
    Object.keys(
      resources.find((r) => r.name === name)!.actions,
    ).map((action) => `"${action}"`),
  )
  .filter((value, index, array) => array.indexOf(value) === index)
  .sort()
  .join(" | ")};

export type ResourceName = ${resourceNames.map((n) => `"${n}"`).join(" | ")};

export type ActionDef = {
  method: string;
  wrapPayload?: boolean;
};

export type ResourceDefinition = {
  name: ResourceName;
  singularName: string;
  pluralName: string;
  actions: Record<string, ActionDef>;
};

export const RESOURCE_DEFINITIONS: Record<ResourceName, ResourceDefinition> = ${JSON.stringify(
  Object.fromEntries(resources.map((r) => [r.name, r])),
  null,
  2,
)} as Record<ResourceName, ResourceDefinition>;
`;

writeFileSync(outputPath, file);
console.log(`Generated ${resources.length} resources -> ${outputPath}`);
